-- Reverses 0014: drops the credit & risk management objects.
DROP VIEW sales.v_credit_exception;
DROP TABLE sales.credit_exception_rule;
DROP FUNCTION sales.queue_credit_filing();
DROP TABLE sales.credit_assessment_snapshot;
DROP TABLE sales.credit_filing_task;
DROP FUNCTION sales.create_credit_assessment(bigint, text);
DROP VIEW sales.v_credit_assessment_due;
DROP VIEW sales.v_credit_subject_inputs;
ALTER TABLE sales.customer_credit_terms DROP CONSTRAINT customer_credit_terms_no_limit;
COMMENT ON COLUMN sales.customer_credit_terms.credit_limit IS NULL;
DROP FUNCTION sales.set_credit_limit(bigint, numeric, text, bigint, text, date);
DROP VIEW sales.v_customer_current_credit_limit;
DROP TABLE sales.customer_credit_limit;
DROP FUNCTION sales.tg_customer_credit_limit_rules();
DROP VIEW sales.v_credit_assessment;
DROP TABLE sales.credit_assessment_line;
DROP TABLE sales.credit_assessment;
DROP FUNCTION sales.credit_arr_exposure(bigint, text);
DROP FUNCTION sales.latest_credit_arr_snapshot();
DROP TABLE sales.credit_arr_line;
DROP TABLE sales.credit_arr_snapshot;
DROP VIEW sales.v_credit_bureau_position;
DROP VIEW sales.v_credit_report;
DROP TABLE sales.credit_report;
DROP TABLE sales.credit_alert_email;
DROP FUNCTION sales.tg_append_only();
DROP TABLE sales.credit_subject;
DELETE FROM sales.policy_setting WHERE setting_key LIKE 'credit\_%';
DROP TABLE sales.credit_risk_band;
DROP TABLE sales.credit_arr_status;
DROP TABLE sales.credit_exposure_rule;
DROP TABLE sales.credit_relationship;
DROP TABLE sales.credit_bureau;
